name: ElevenLabs Document Assignment (Phase 2)

on:
  schedule:
    # Run every 15 minutes to assign uploaded documents to agents
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual triggering

concurrency:
  group: elevenlabs-assign-documents
  cancel-in-progress: false  # Don't cancel if another run is in progress

jobs:
  assign-documents:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Allow up to 1 hour for RAG indexing delays
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Assign Documents to Agents (Phase 2)
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        run: |
          echo "Starting ElevenLabs Phase 2 (Document Assignment)..."
          
          # Check if ElevenLabs API key is available
          if [ -z "$ELEVENLABS_API_KEY" ]; then
            echo "Warning: ELEVENLABS_API_KEY not set, skipping document assignment"
            exit 0
          fi
          
          # Check if agent config exists
          if [ ! -f "config/elevenlabs-agents.json" ]; then
            echo "Warning: config/elevenlabs-agents.json not found, skipping document assignment"
            exit 0
          fi
          
          # Run Phase 2: Assign uploaded documents to agents
          echo "Running ElevenLabs Phase 2 (Assign Documents to Agents)..."
          python3 scripts/elevenlabs_two_phase_sync.py assign
          
          echo "ElevenLabs Phase 2 (Assignment) completed successfully"
          
      - name: Report Results
        if: always()
        run: |
          echo "Document assignment job completed"
          echo "Check the logs above for detailed results"
