name: Update Product Data

on:
  repository_dispatch:
    types: [product-updated, product-added, product-removed]
  workflow_dispatch:
  push:
    paths:
      - 'out/**/manifest.json'
      - 'out/**/llms-index.json'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Update products
        env:
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
        run: |
          echo "Action: ${{ github.event.action }}"
          echo "URLs: ${{ github.event.client_payload.urls }}"
          
          # Check if this is a repository_dispatch event
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            case "${{ github.event.action }}" in
              "product-added")
                python3 scripts/update_llms_sharded.py https://www.mydiy.ie \
                  --added '${{ github.event.client_payload.urls }}'
                ;;
              "product-updated")
                python3 scripts/update_llms_sharded.py https://www.mydiy.ie \
                  --changed '${{ github.event.client_payload.urls }}'
                ;;
              "product-removed")
                python3 scripts/update_llms_sharded.py https://www.mydiy.ie \
                  --removed '${{ github.event.client_payload.urls }}'
                ;;
            esac
          else
            # For push events, run the sharded update script for all sites
            echo "Running sharded update for all sites..."
            # Process jgengineering.ie with full crawl
            python3 scripts/update_llms_sharded.py https://www.jgengineering.ie --full
            # Process mydiy.ie with full crawl (if it exists)
            if [ -d "out/mydiy.ie" ]; then
              python3 scripts/update_llms_sharded.py https://www.mydiy.ie --full
            fi
          fi
          
      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-update: ${{ github.event_name }} - ${{ github.event.action || 'push' }}"
          git push
          
      - name: Deploy to ElevenLabs
        if: steps.changes.outputs.changes == 'true'
        run: |
          echo "Files updated, would deploy to ElevenLabs here"
          # rsync -av --update out/llms-full.*.txt ${{ secrets.ELEVENLABS_SERVER }}:/data/